version: 2

project_name: xenvsync

before:
  hooks:
    - go mod tidy
    - go vet ./...

builds:
  - main: .
    binary: xenvsync
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    homepage: "https://github.com/nasimstg/xenvsync"
    description: "A fast CLI to securely encrypt, sync, and inject environment variables."
    maintainer: "Md Nasim Sheikh <nasim.stg@gmail.com>"
    license: "MIT"
    formats:
      - deb
      - rpm
      - apk

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

release:
  github:
    owner: nasimstg
    name: xenvsync
  draft: false
  prerelease: auto
