import { CodeBlock } from "@/components/CodeBlock";
import { Card, PageHeader, Section } from "@/components/DocsComponents";
import Link from "next/link";

export const metadata = {
  title: "Inside xenvsync: AES-256-GCM Encryption and X25519 Team Sharing",
  description:
    "A technical deep dive into xenvsync's cryptographic model: AES-256-GCM vault format, nonce generation, GCM authentication tags, X25519 ECDH key exchange for team vaults, passphrase-based key encryption with scrypt, and memory zeroing.",
  openGraph: {
    title: "Inside xenvsync: AES-256-GCM Encryption and X25519 Team Sharing",
    description: "The vault format, cryptographic primitives, and security design decisions behind xenvsync.",
    url: "https://xenvsync.softexforge.io/blog/technical-deep-dive",
  },
  alternates: { canonical: "https://xenvsync.softexforge.io/blog/technical-deep-dive" },
};

export default function TechnicalDeepDivePost() {
  return (
    <article className="max-w-4xl mx-auto px-4 sm:px-6 py-12 space-y-10">
      <PageHeader
        title="Inside xenvsync: AES-256-GCM Encryption and X25519 Team Sharing"
        description="Published March 28, 2026 · 12 min read · Technical Deep Dive"
      />

      <Section title="Design Goals">
        <Card className="text-sm text-[var(--color-text-secondary)] leading-relaxed space-y-3">
          <p>
            xenvsync was built around three non-negotiable security properties:
          </p>
          <ol className="space-y-1 ml-3 mt-2">
            {[
              "Authenticated encryption — any tampering with the vault must be detectable before decryption proceeds.",
              "Fresh randomness — encrypting the same plaintext twice must produce different ciphertext, with no nonce reuse.",
              "Local key custody — decryption material must never leave the local machine or pass through a third-party service.",
            ].map((item, i) => (
              <li key={i} className="flex gap-2">
                <span className="text-[var(--color-accent)] font-bold shrink-0">{i + 1}.</span>
                <span>{item}</span>
              </li>
            ))}
          </ol>
          <p className="mt-2">
            AES-256-GCM satisfies all three. The team sharing layer adds a fourth property: per-member key isolation using X25519 ECDH, so no symmetric secret is ever distributed across a team.
          </p>
        </Card>
      </Section>

      <Section title="V1 Vault Format: Symmetric Encryption">
        <Card className="text-sm text-[var(--color-text-secondary)] leading-relaxed space-y-3">
          <p>
            For solo use (no team roster), xenvsync uses V1: a single AES-256-GCM symmetric key stored at <code>.xenvsync.key</code> with 0600 permissions. The vault file is a base64-encoded blob wrapped in ASCII header and footer markers.
          </p>
          <p>
            The binary layout inside the base64 encoding is:
          </p>
        </Card>
        <CodeBlock language="text" title="V1 binary vault layout">
{`[ 12-byte nonce ][ ciphertext (variable length) ][ 16-byte GCM tag ]

Total overhead: 28 bytes + plaintext length
Base64-encoded and wrapped with:
  -----BEGIN XENVSYNC VAULT-----
  <base64 payload>
  -----END XENVSYNC VAULT-----`}
        </CodeBlock>
        <Card className="text-sm text-[var(--color-text-secondary)] leading-relaxed space-y-3">
          <p>
            <strong className="text-[var(--color-text)]">Nonce:</strong> 12 bytes generated from <code>crypto/rand</code> — Go&apos;s cryptographically secure random source backed by the operating system. A fresh nonce is generated on every <code>xenvsync push</code>, ensuring ciphertext is non-deterministic even when the plaintext has not changed.
          </p>
          <p>
            <strong className="text-[var(--color-text)]">AES-256-GCM:</strong> The 256-bit key encrypts the serialized <code>.env</code> content. GCM (Galois/Counter Mode) is an authenticated encryption with associated data (AEAD) scheme — it produces both a ciphertext and a 16-byte authentication tag. The tag covers the full ciphertext and nonce. If any byte of the vault is modified, decryption fails with an authentication error rather than silently returning corrupted plaintext.
          </p>
          <p>
            <strong className="text-[var(--color-text)]">Key size:</strong> The symmetric key is exactly 32 bytes (256 bits), generated by <code>crypto/rand.Read</code>. Keys shorter than this are rejected by <code>doctor</code>.
          </p>
        </Card>
      </Section>

      <Section title="V2 Vault Format: Per-Member Key Slots">
        <Card className="text-sm text-[var(--color-text-secondary)] leading-relaxed space-y-3">
          <p>
            When a <code>.xenvsync-team.json</code> roster exists, xenvsync upgrades to V2 format. The vault now contains a JSON header with per-member key slots, followed by the same AES-256-GCM encrypted payload.
          </p>
          <p>
            The core idea: a single symmetric data encryption key (DEK) encrypts the payload. For each team member, an ephemeral X25519 key pair performs an ECDH exchange with the member&apos;s long-term public key. The shared secret derived from this exchange encrypts the DEK. Each member gets their own slot containing the ephemeral public key and the encrypted DEK.
          </p>
        </Card>
        <CodeBlock language="text" title="V2 vault structure">
{`-----BEGIN XENVSYNC V2 VAULT-----
[JSON key slot array]
{"slots": [
  {
    "name": "alice",
    "ephemeralPublicKey": "<base64url>",
    "encryptedKey": "<base64url>"
  },
  {
    "name": "bob",
    "ephemeralPublicKey": "<base64url>",
    "encryptedKey": "<base64url>"
  }
]}
---DATA---
<base64-encoded AES-256-GCM ciphertext (same layout as V1)>
-----END XENVSYNC V2 VAULT-----`}
        </CodeBlock>
        <Card className="text-sm text-[var(--color-text-secondary)] leading-relaxed space-y-3">
          <p>
            <strong className="text-[var(--color-text)]">X25519 ECDH key exchange:</strong> X25519 is the Diffie-Hellman function over Curve25519. It takes a private key and a public key and produces a 32-byte shared secret. For each push operation, xenvsync generates a fresh ephemeral private key, computes <code>ECDH(ephemeral_private, member_public)</code>, and uses the result (via HKDF expansion) to encrypt the DEK with AES-256-GCM.
          </p>
          <p>
            <strong className="text-[var(--color-text)]">Why ephemeral keys?</strong> Using a fresh ephemeral keypair per push means that even if the DEK slot is somehow decrypted, it provides no information about previous vault versions. Each push generates completely independent key material for every slot. This is forward secrecy at the vault level.
          </p>
          <p>
            <strong className="text-[var(--color-text)]">Decryption:</strong> A member runs <code>xenvsync pull</code>. Their identity&apos;s private key is at <code>~/.xenvsync/identity</code> (0600 permissions). xenvsync scans the slot list for their name, computes <code>ECDH(identity_private, slot.ephemeralPublicKey)</code> to recover the shared secret, decrypts the DEK, then uses the DEK to decrypt the payload. The DEK never leaves the member&apos;s machine.
          </p>
        </Card>
      </Section>

      <Section title="Passphrase-Protected Keys">
        <Card className="text-sm text-[var(--color-text-secondary)] leading-relaxed space-y-3">
          <p>
            For additional protection of the key file itself, <code>xenvsync init --passphrase</code> wraps the symmetric key with a key-encryption-key (KEK) derived from a user passphrase.
          </p>
        </Card>
        <CodeBlock language="text" title="Passphrase key derivation">
{`KEK = scrypt(passphrase, salt, N=32768, r=8, p=1, keyLen=32)
encrypted_key = AES-256-GCM(KEK, key_material)

Stored as: "enc:" + base64(salt || nonce || ciphertext || tag)

Runtime: XENVSYNC_PASSPHRASE env var → derive KEK → decrypt key → proceed`}
        </CodeBlock>
        <Card className="text-sm text-[var(--color-text-secondary)] leading-relaxed space-y-3">
          <p>
            <strong className="text-[var(--color-text)]">scrypt parameters:</strong> N=32768 (2^15) work factor, r=8 block size, p=1 parallelization. These parameters require ~32 MB of memory per derivation attempt, making offline dictionary attacks expensive. The salt is generated fresh per key file.
          </p>
          <p>
            This provides defense in depth: even if <code>.xenvsync.key</code> is leaked, it cannot be used without the passphrase.
          </p>
        </Card>
      </Section>

      <Section title="Memory Hygiene">
        <Card className="text-sm text-[var(--color-text-secondary)] leading-relaxed space-y-3">
          <p>
            xenvsync zeroes out key material after use via <code>crypto.ZeroBytes</code>, which overwrites the byte slice with zeros before letting the garbage collector reclaim it. This limits the window during which key material exists in process memory and reduces the risk of it persisting in a core dump or memory snapshot.
          </p>
          <p>
            <code>xenvsync run</code> is the most security-sensitive command: it decrypts the vault in memory, merges the env pairs into the child process environment, spawns the child, and immediately zeroes the key material. The child process inherits only the environment variables — never the key.
          </p>
        </Card>
        <CodeBlock language="go" title="Memory zeroing pattern (internal/crypto/zero.go)">
{`// ZeroBytes overwrites a byte slice with zeros
// to limit key material residency in memory.
func ZeroBytes(b []byte) {
    for i := range b {
        b[i] = 0
    }
}`}
        </CodeBlock>
      </Section>

      <Section title="Key Rotation Security Properties">
        <Card className="text-sm text-[var(--color-text-secondary)] leading-relaxed space-y-3">
          <p>
            <code>xenvsync rotate</code> decrypts the current vault, generates fresh key material, and re-encrypts in one atomic step. The ordering matters: the vault is written first, then the key file. If the key write fails, the old key can still decrypt the old vault. This prevents a scenario where the vault has been updated to use a new key that was never saved.
          </p>
          <p>
            In V2 mode, rotation generates fresh ephemeral X25519 keys for all current roster members. The <code>--revoke &lt;name&gt;</code> flag removes a member from the roster before re-encryption, effectively excluding them from all future decryption. Their existing private key can still decrypt historical vaults committed before the rotation — which is why immediate rotation after offboarding is essential.
          </p>
        </Card>
      </Section>

      <Section title="Threat Model">
        <div className="space-y-3">
          {[
            {
              threat: "Vault committed to public repo",
              mitigation: "AES-256-GCM ciphertext is computationally infeasible to decrypt without the key. GCM tag ensures tamper detection.",
            },
            {
              threat: "Key file leaked (no passphrase)",
              mitigation: "Attacker can decrypt all vaults encrypted with that key. Immediate rotation invalidates the key for future vaults.",
            },
            {
              threat: "Key file leaked (passphrase protected)",
              mitigation: "Attacker must brute-force scrypt(N=32768) — expensive. Rotate key after confirmed exposure.",
            },
            {
              threat: "Team member with access leaks secrets",
              mitigation: "Per-member key slots limit blast radius to that member's identity. Rotate to exclude compromised identity.",
            },
            {
              threat: "Vault file tampered in transit",
              mitigation: "GCM authentication tag detects any modification. xenvsync verify catches this explicitly.",
            },
            {
              threat: "Nonce reuse producing repeated ciphertext",
              mitigation: "12-byte nonce from crypto/rand per operation. Probability of collision across 2^48 operations is negligible.",
            },
          ].map(({ threat, mitigation }) => (
            <Card key={threat} className="space-y-1">
              <p className="text-sm font-semibold text-[var(--color-text)]">{threat}</p>
              <p className="text-sm text-[var(--color-text-secondary)] leading-relaxed">{mitigation}</p>
            </Card>
          ))}
        </div>
      </Section>

      <Section title="Further Reading">
        <div className="flex flex-wrap gap-2">
          <Link href="/docs/security" className="text-sm text-[var(--color-accent)] hover:underline">Security Model docs</Link>
          <Link href="/blog/tool-comparison" className="text-sm text-[var(--color-accent)] hover:underline ml-4">Tool comparison</Link>
        </div>
      </Section>
    </article>
  );
}
